---
- hosts: server
  tasks:
    # task 1
    - name: test connection
      ping:
      register: message

    # task 2
    - name: print debug message
      debug:
        msg: "{{ message }}"
        
    # task 3
    - name: copy JAR file
      copy: 
        src: ~/petclinic/spring-petclinic/target/spring-petclinic-2.6.0-SNAPSHOT.jar
        dest: /home/vagrant/spring-petclinic-2.6.0-SNAPSHOT.jar
